[workspace]
members = [".", "tui"]

[package]
name = "windfish"
version = "0.1.0"
edition = "2024"
authors = ["git@qrsnap.io"]

[dependencies]
bitcoin = "0.32.8"
chrono = "0.4.42"
byteorder = "1.5.0"
thiserror = "2.0.17"
